name: Run Tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - ubuntu-24.04
          - windows-2022
        node-version:
          - '20'
    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm clean-install
      - name: Lint code
        run: npm run lint
      - name: Run unit tests
        run: npm run test
      - name: Test deploy
        run: npm publish --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_DEPLOY_TOKEN}}
