name: Publish to NPM

on:
  release:
    types:
      - published
      - edited

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        node-version:
          - '14'
    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          cache: yarn
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      # Let's do tests rq just to make sure we dont push something that is fundamentally broken
      - name: Lint code
        run: yarn lint
      - name: Run unit tests
        run: yarn test

      # Deploy
      - name: Deploy and publish release to npm
        run: |
          if [ "${{ github.event.release.prerelease }}" ==  "false" ]; then
            npm publish --access public --dry-run
            # npm publish --access public --dry-run
            ::notice title=Deployed stable release::Pushed latest release @lando/${{ github.event.repository.name }}@${{ github.ref_name }}
          else
            npm publish --access public --tag beta --dry-run
            npm publish --access public --tag edge --dry-run
            npm publish --access public --tag next --dry-run
            ::notice title=Deployed stable release::Pushed next release @lando/${{ github.event.repository.name }}@${{ github.ref_name }}
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_DEPLOY_TOKEN}}
