name: Publish to NPM

on:
  release:
    types:
      - published
      - edited

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        node-version:
          - '14'
        pre-release-tag: edge

    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          cache: yarn
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      # Let's do tests rq just to make sure we dont push something that is fundamentally broken
      - name: Lint code
        run: yarn lint
      - name: Run unit tests
        run: yarn test

      # Deploy
      - name: Publish to npm
        run: |
          # Unpublish if this was edited because we will need to publish to a different tag
          if [ "${{ github.event.action }}" ==  "edited" ]; then
            npm unpublish @${{ github.repository }}@${{ github.ref_name }} --dry-run
            npm unpublish @${{ github.repository }}@${{ github.ref_name }}
            echo "::notice title=Unpublished previous @${{ github.repository }}@${{ github.ref_name }} release::This is an edited release so we are unpublishing the previous version of this release so we can publish it to a new tag."
          fi

          # Publish based on release type
          if [ "${{ github.event.release.prerelease }}" ==  "false" ]; then
            npm publish --access public --dry-run
            npm publish --access public
            echo "::notice title=Published ${{ github.ref_name }} to @${{ github.repository }}::This is a stable release published to the default 'latest' npm tag"
          else
            npm publish --access public --tag ${{ matrix.pre-release-tag }} --dry-run
            npm publish --access public --tag ${{ matrix.pre-release-tag }}
            echo "::notice title=Published ${{ github.ref_name }} to @${{ github.repository }}@${{ matrix.pre-release-tag }}::This is a pre-release published to the '${{ matrix.pre-release-tag }} npm tag"
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_DEPLOY_TOKEN}}
